version = "3.11.0"
runner.dialect = scala212source3
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
docstrings.wrap = "yes"
project.git = true
align.preset = none
align.stripMargin = true
newlines.source=unfold
